-- --------------------------------------------------------------------------------------------------------------------------

-- DATABASE 

CREATE DATABASE project_class;
USE project_class;

-- ----------------------------------------------------------------------------------------------------------------------------

-- TABLES

-- SUPPLIERS
CREATE TABLE SUPPLIERS (
  SUPPLIER_ID INT PRIMARY KEY AUTO_INCREMENT,
  SUPPLIER_NAME VARCHAR(50) NOT NULL
);

-- CUSTOMERS
CREATE TABLE CUSTOMERS (
  CUSTOMER_ID INT PRIMARY KEY AUTO_INCREMENT,
  CUSTOMER_NAME VARCHAR(100) NOT NULL
);

-- RAW MATERIALS
CREATE TABLE RAW_MATERIALS (
  MATERIAL_ID INT PRIMARY KEY AUTO_INCREMENT,
  MATERIAL_NAME VARCHAR(100) NOT NULL,
  MATERIAL_GRADE VARCHAR(50),
  UNIQUE (MATERIAL_NAME, MATERIAL_GRADE)
);

-- MACHINES
CREATE TABLE MACHINES (
  MACHINE_ID INT PRIMARY KEY AUTO_INCREMENT,
  MACHINE_NAME VARCHAR(50) NOT NULL,
  MACHINE_TYPE VARCHAR(50),
  PLANT_ID VARCHAR(10) NOT NULL,
  LAST_MAINTAINANCE_DATE DATE
);

-- PRODUCTION ORDERS
CREATE TABLE PRODUCTION_ORDERS (
  PRODUCTION_ID INT PRIMARY KEY AUTO_INCREMENT,
  PRODUCTION_CODE VARCHAR(20) UNIQUE,
  CUSTOMER_ID INT NOT NULL,
  COMPONENT_TO_PRODUCE VARCHAR(255) NOT NULL,
  QUANTITY_TO_PRODUCE INT NOT NULL,
  ORDER_DATE DATETIME NOT NULL,
  SCHEDULED_START_DATE DATETIME NOT NULL,
  SCHEDULED_END_DATE DATETIME NOT NULL,
  STATUS_ VARCHAR(50) NOT NULL,
  ASSIGNED_MACHINE_ID INT,
  PLANT_ID VARCHAR(10) NOT NULL,
  FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID),
  FOREIGN KEY (ASSIGNED_MACHINE_ID) REFERENCES MACHINES(MACHINE_ID),
  CHECK (STATUS_ IN ('Scheduled','In Progress','Complete',
                    'On Hold','Cancelled','Rework Required',
                    'Quoted','Pending Materials','Rework Completed')),
  CHECK (SCHEDULED_START_DATE >= ORDER_DATE),
  CHECK (SCHEDULED_END_DATE >= SCHEDULED_START_DATE)
);

-- MATERIAL INVENTORY
CREATE TABLE MATERIAL_INVENTORY (
  BATCH_ID INT PRIMARY KEY AUTO_INCREMENT,
  ORIGINAL_BATCH_ID VARCHAR(50) UNIQUE,
  MATERIAL_ID INT NOT NULL,
  SUPPLIER_ID INT NOT NULL,
  RECEIVED_DATE DATE NOT NULL,
  INITIAL_QUANTITY DECIMAL(10,2) NOT NULL,
  REMAINING_QUANTITY DECIMAL(10,2),
  UNIT VARCHAR(10) NOT NULL,
  FOREIGN KEY (MATERIAL_ID) REFERENCES RAW_MATERIALS(MATERIAL_ID),
  FOREIGN KEY (SUPPLIER_ID) REFERENCES SUPPLIERS(SUPPLIER_ID),
  CHECK (UNIT IN ('KG','M','PCS','FT','SQ_FT','LBS'))
);

-- PRODUCTION MATERIAL USAGE
CREATE TABLE PRODUCTION_MATERIAL_USAGE (
  Usage_ID INT PRIMARY KEY AUTO_INCREMENT,
  Production_Order_ID INT NOT NULL,
  Batch_ID INT NOT NULL,
  Quantity_Used DECIMAL(10,2),
  Material_ID INT NOT NULL,
  FOREIGN KEY (Production_Order_ID) REFERENCES PRODUCTION_ORDERS(PRODUCTION_ID),
  FOREIGN KEY (Batch_ID) REFERENCES MATERIAL_INVENTORY(BATCH_ID),
  FOREIGN KEY (Material_ID) REFERENCES RAW_MATERIALS(MATERIAL_ID)
);

-- EMPLOYEES
CREATE TABLE EMPLOYEES (
   Employee_ID INT PRIMARY KEY AUTO_INCREMENT,
   Full_Name VARCHAR(100) NOT NULL,
   Role VARCHAR(50) NOT NULL
);

-- QUALITY CHECKS
CREATE TABLE Quality_checks (
    Quality_checkid INT PRIMARY KEY AUTO_INCREMENT,
    Origianl_Quality_Check_ID VARCHAR(50),
    Production_Order_ID INT NOT NULL,
    Inspector_ID INT NOT NULL,
    Check_Time_Stamp DATETIME,
    Results VARCHAR(20),
    FOREIGN KEY (Production_Order_ID) REFERENCES PRODUCTION_ORDERS(PRODUCTION_ID),
    FOREIGN KEY (Inspector_ID) REFERENCES EMPLOYEES(Employee_ID)
);

-- LOW STOCK LOG
CREATE TABLE Material_Low_StockLog (
    Log_ID INT PRIMARY KEY AUTO_INCREMENT,
    Material_ID INT NOT NULL,
    Material_Name VARCHAR(100),
    Material_Grade VARCHAR(50),
    Alert_Trigger_Quantity DECIMAL(10,2),
    Quantity_To_Order DECIMAL(10,2),
    Alert_Date DATETIME DEFAULT NOW()
);

-- ------------------------------------------------------------------------------------------------------------------------

-- TRIGGERS

DELIMITER $$
-- QUALITY FAIL → UPDATE STATUS
CREATE TRIGGER update_Production_Status_onfail
AFTER INSERT ON Quality_checks
FOR EACH ROW
BEGIN
   IF NEW.Results = 'Failed' THEN
      UPDATE PRODUCTION_ORDERS
      SET STATUS = 'Rework Required'
      WHERE PRODUCTION_ID = NEW.Production_Order_ID;
   END IF;
END $$

-- UPDATE MATERIAL REMAINING
CREATE TRIGGER trg_update_material_Remaining
AFTER INSERT ON PRODUCTION_MATERIAL_USAGE
FOR EACH ROW
BEGIN
   UPDATE MATERIAL_INVENTORY
   SET REMAINING_QUANTITY = REMAINING_QUANTITY - NEW.Quantity_Used
   WHERE BATCH_ID = NEW.Batch_ID
   AND MATERIAL_ID = NEW.Material_Id;
   IF (SELECT REMAINING_QUANTITY 
       FROM MATERIAL_INVENTORY 
       WHERE BATCH_ID = NEW.Batch_ID 
       AND MATERIAL_ID = NEW.Material_Id) < 0 THEN
       SIGNAL SQLSTATE '45000'
       SET MESSAGE_TEXT = 'Insufficient material';
   END IF;
END $$

-- MACHINE SCHEDULE CONFLICT CHECK
CREATE TRIGGER trg_Check_Machine_Schedule
BEFORE INSERT ON PRODUCTION_ORDERS
FOR EACH ROW
BEGIN
   IF EXISTS (
        SELECT 1
        FROM PRODUCTION_ORDERS AS p
        WHERE p.Assigned_Machine_ID = NEW.Assigned_Machine_ID
        AND p.STATUS_ NOT IN ('Completed','Cancelled')
        AND NEW.SCHEDULED_START_DATE < p.SCHEDULED_END_DATE
        AND NEW.SCHEDULED_END_DATE > p.SCHEDULED_START_DATE
   )
   THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Schedule conflict: Machine already occupied.';
   END IF;
END $$

-- LOW STOCK ALERT
CREATE TRIGGER TRG_LOWSTOCK
AFTER UPDATE ON MATERIAL_INVENTORY
FOR EACH ROW
BEGIN
   IF NEW.REMAINING_QUANTITY < 500 THEN
      INSERT INTO Material_Low_StockLog
      (Material_ID, Material_Name, Material_Grade,
       Alert_Trigger_Quantity, Quantity_To_Order)
      SELECT 
         NEW.MATERIAL_ID,
         MATERIAL_NAME,
         MATERIAL_GRADE,
         NEW.REMAINING_QUANTITY,
         (4000 - NEW.REMAINING_QUANTITY)
      FROM RAWMATERIALS
      WHERE MATERIAL_ID = NEW.MATERIAL_ID;
   END IF;
END $$
DELIMITER ;
